language: ruby
sudo: required
services:
  - docker
rvm:
  - 2.3
env:
  - IMAGE=centos:7
  - IMAGE=debian:jessie
  - IMAGE=debian:stretch
bundler_args: "--jobs=4"
cache: bundler
before_install:
  - travis_retry gem update --system || travis_retry gem update --system 2.7.8
  - travis_retry gem install bundler --no-document || travis_retry gem install bundler --no-document -v 1.17.3
script:
  - bundle exec itamae docker --node-yaml=recipes/node.yml recipes/install.rb --image=$IMAGE --tag itamae-plugin:latest
  - DOCKER_IMAGE=itamae-plugin:latest bundle exec rspec
branches:
  only:
    - master
notifications:
  email: false
  slack:
    secure: gw0uGSbbRkiO+wt4/bcddU8pz3Hj9P1XQY2k5bG4QalmY0OR8YEVch7LcqbzEhYehO0VUGhOJ8D2shAnCmhFoDvUkrGIRWQBcAmCuMDbSJDkB2CwU6wmi3ucid/wV+i6H0bWHyn86FSqpe/WlrMk2Gaf8j0qQHtTUx4rK73+PJk=
