language: ruby
rvm:
- 2.1
- 2.2
- ruby-head
cache: bundler
before_install: gem install bundler
before_script:
- export COVERAGE=true
script:
- bundle exec rspec
branches:
  only:
  - master
notifications:
  email: false
  slack:
    secure: SusEtW3pV+b+KUQoQjhqTI+7QtaDXlVl0Wx2EPo1VA4k/t9M/FRZXAXxq2j5+K3QE0y4p4QbnMRoZ8W8l4f7NXzOi7CFHQAnKUVDswZdsj2udEWeNWUeN4Rub0de3sInfKkbZKfT0uhamToX/pRH7uhOogeL9Eei+KUekUXJKTE=
matrix:
  allow_failures:
  - rvm: ruby-head
sudo: false
